name: create-pull-request

on:
  push:
    branches-ignore:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Test Build
        run: bun install && bun run next build

      - name: Get Commit Count
        id: get_commit_count
        run: echo "commit_count=$(git rev-list --count HEAD ^origin/main)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: branch `${{ github.ref_name }}` wants to merge ${{ steps.get_commit_count.outputs.commit_count }} commits into `main`
          commit-message: branch `${{ github.ref_name }}` wants to merge ${{ steps.get_commit_count.outputs.commit_count }} commits into `main`
          body: This pull request was created automatically by GitHub Actions. It will merge ${{ steps.get_commit_count.outputs.commit_count }} commits into `main`.
